# Makefile
# Running Octave script Makefile.
# Vladimir Rutsky <altsysrq@gmail.com>
# 17.03.2009

SOURCE=golden_section_search.m

all:
	@echo "Use 'make run' to run Octave's script."

run:
	octave -q $(SOURCE)
